export const AVAILABLE_ADVANTAGES = [
  { key: "accurateAttack", name: "Accurate Attack", maxRank: 1 },
  { key: "agilityBonus", name: "Agile Feint", maxRank: 1 },
  { key: "allOutAttack", name: "All-out Attack", maxRank: 1 },
  { key: "assessment", name: "Assessment", maxRank: 1 },
  { key: "benefit", name: "Benefit", maxRank: null, hasDetails: true },
  { key: "closeAttack", name: "Close Attack", maxRank: null },
  { key: "daze", name: "Daze", maxRank: 1 },
  { key: "defensiveAttack", name: "Defensive Attack", maxRank: 1 },
  { key: "defensiveRoll", name: "Defensive Roll", maxRank: null },
  { key: "diehard", name: "Diehard", maxRank: 1 },
  { key: "eideticMemory", name: "Eidetic Memory", maxRank: 1 },
  { key: "equipment", name: "Equipment", maxRank: null, hasDetails: true },
  { key: "evasion", name: "Evasion", maxRank: 2 },
  { key: "extraordinaryEffort", name: "Extraordinary Effort", maxRank: 1 },
  { key: "fascinate", name: "Fascinate", maxRank: 1, hasDetails: true },
  {
    key: "favoredEnvironment",
    name: "Favored Environment",
    maxRank: 1,
    hasDetails: true,
  },
  { key: "favoredFoe", name: "Favored Foe", maxRank: 1, hasDetails: true },
  {
    key: "improvedCritical",
    name: "Improved Critical",
    maxRank: 4,
    hasDetails: true,
  },
  { key: "improvedInitiative", name: "Improved Initiative", maxRank: null },
  { key: "powerAttack", name: "Power Attack", maxRank: 1 },
  { key: "rangedAttack", name: "Ranged Attack", maxRank: null },
  { key: "takedown", name: "Takedown", maxRank: 2 },
  { key: "uncannyDodge", name: "Uncanny Dodge", maxRank: 1 },
];
